export const FETCH_PIECES_REQUEST = 'FETCH_PIECES_REQUEST';
export const FETCH_PIECES_SUCCESS = 'FETCH_PIECES_SUCCESS';
export const FETCH_PIECES_FAILURE = 'FETCH_PIECES_FAILURE';

export const FETCH_PIECE_BY_ID_REQUEST = 'FETCH_PIECE_BY_ID_REQUEST';
export const FETCH_PIECE_BY_ID_SUCCESS = 'FETCH_PIECE_BY_ID_SUCCESS';
export const FETCH_PIECE_BY_ID_FAILURE = 'FETCH_PIECE_BY_ID_FAILURE';

export const CREATE_PIECE_REQUEST = 'CREATE_PIECE_REQUEST';
export const CREATE_PIECE_SUCCESS = 'CREATE_PIECE_SUCCESS';
export const CREATE_PIECE_FAILURE = 'CREATE_PIECE_FAILURE';

export const UPDATE_PIECE_REQUEST = 'UPDATE_PIECE_REQUEST';
export const UPDATE_PIECE_SUCCESS = 'UPDATE_PIECE_SUCCESS';
export const UPDATE_PIECE_FAILURE = 'UPDATE_PIECE_FAILURE';

export const DELETE_PIECE_REQUEST = 'DELETE_PIECE_REQUEST';
export const DELETE_PIECE_SUCCESS = 'DELETE_PIECE_SUCCESS';
export const DELETE_PIECE_FAILURE = 'DELETE_PIECE_FAILURE';

export const CLEAR_CREATED_PIECE = 'CLEAR_CREATED_PIECE'; 

// Piece Materials Types
export const FETCH_PIECE_MATERIALS_REQUEST = 'FETCH_PIECE_MATERIALS_REQUEST';
export const FETCH_PIECE_MATERIALS_SUCCESS = 'FETCH_PIECE_MATERIALS_SUCCESS';
export const FETCH_PIECE_MATERIALS_FAILURE = 'FETCH_PIECE_MATERIALS_FAILURE';

export const ADD_PIECE_MATERIAL_REQUEST = 'ADD_PIECE_MATERIAL_REQUEST';
export const ADD_PIECE_MATERIAL_SUCCESS = 'ADD_PIECE_MATERIAL_SUCCESS';
export const ADD_PIECE_MATERIAL_FAILURE = 'ADD_PIECE_MATERIAL_FAILURE';

export const REMOVE_PIECE_MATERIAL_REQUEST = 'REMOVE_PIECE_MATERIAL_REQUEST';
export const REMOVE_PIECE_MATERIAL_SUCCESS = 'REMOVE_PIECE_MATERIAL_SUCCESS';
export const REMOVE_PIECE_MATERIAL_FAILURE = 'REMOVE_PIECE_MATERIAL_FAILURE';

export const UPDATE_PIECE_MATERIALS_REQUEST = 'UPDATE_PIECE_MATERIALS_REQUEST';
export const UPDATE_PIECE_MATERIALS_SUCCESS = 'UPDATE_PIECE_MATERIALS_SUCCESS';
export const UPDATE_PIECE_MATERIALS_FAILURE = 'UPDATE_PIECE_MATERIALS_FAILURE'; 