// Fetch materials for a proposal item piece
export const FETCH_PROPOSAL_ITEM_PIECE_MATERIALS_REQUEST = 'FETCH_PROPOSAL_ITEM_PIECE_MATERIALS_REQUEST';
export const FETCH_PROPOSAL_ITEM_PIECE_MATERIALS_SUCCESS = 'FETCH_PROPOSAL_ITEM_PIECE_MATERIALS_SUCCESS';
export const FETCH_PROPOSAL_ITEM_PIECE_MATERIALS_FAILURE = 'FETCH_PROPOSAL_ITEM_PIECE_MATERIALS_FAILURE';

// Add material to a proposal item piece
export const ADD_PROPOSAL_ITEM_PIECE_MATERIAL_REQUEST = 'ADD_PROPOSAL_ITEM_PIECE_MATERIAL_REQUEST';
export const ADD_PROPOSAL_ITEM_PIECE_MATERIAL_SUCCESS = 'ADD_PROPOSAL_ITEM_PIECE_MATERIAL_SUCCESS';
export const ADD_PROPOSAL_ITEM_PIECE_MATERIAL_FAILURE = 'ADD_PROPOSAL_ITEM_PIECE_MATERIAL_FAILURE';

// Remove material from a proposal item piece
export const REMOVE_PROPOSAL_ITEM_PIECE_MATERIAL_REQUEST = 'REMOVE_PROPOSAL_ITEM_PIECE_MATERIAL_REQUEST';
export const REMOVE_PROPOSAL_ITEM_PIECE_MATERIAL_SUCCESS = 'REMOVE_PROPOSAL_ITEM_PIECE_MATERIAL_SUCCESS';
export const REMOVE_PROPOSAL_ITEM_PIECE_MATERIAL_FAILURE = 'REMOVE_PROPOSAL_ITEM_PIECE_MATERIAL_FAILURE';

// Update all materials for a proposal item piece
export const UPDATE_PROPOSAL_ITEM_PIECE_MATERIALS_REQUEST = 'UPDATE_PROPOSAL_ITEM_PIECE_MATERIALS_REQUEST';
export const UPDATE_PROPOSAL_ITEM_PIECE_MATERIALS_SUCCESS = 'UPDATE_PROPOSAL_ITEM_PIECE_MATERIALS_SUCCESS';
export const UPDATE_PROPOSAL_ITEM_PIECE_MATERIALS_FAILURE = 'UPDATE_PROPOSAL_ITEM_PIECE_MATERIALS_FAILURE'; 