export const FETCH_MANUFACTURERS_REQUEST = "FETCH_MANUFACTURERS_REQUEST";
export const FETCH_MANUFACTURERS_SUCCESS = "FETCH_MANUFACTURERS_SUCCESS";
export const FETCH_MANUFACTURERS_FAILURE = "FETCH_MANUFACTURERS_FAILURE";

export const FETCH_MANUFACTURER_BY_ID_REQUEST =
  "FETCH_MANUFACTURER_BY_ID_REQUEST";
export const FETCH_MANUFACTURER_BY_ID_SUCCESS =
  "FETCH_MANUFACTURER_BY_ID_SUCCESS";
export const FETCH_MANUFACTURER_BY_ID_FAILURE =
  "FETCH_MANUFACTURER_BY_ID_FAILURE";

export const CREATE_MANUFACTURER_REQUEST = "CREATE_MANUFACTURER_REQUEST";
export const CREATE_MANUFACTURER_SUCCESS = "CREATE_MANUFACTURER_SUCCESS";
export const CREATE_MANUFACTURER_FAILURE = "CREATE_MANUFACTURER_FAILURE";

export const UPDATE_MANUFACTURER_REQUEST = "UPDATE_MANUFACTURER_REQUEST";
export const UPDATE_MANUFACTURER_SUCCESS = "UPDATE_MANUFACTURER_SUCCESS";
export const UPDATE_MANUFACTURER_FAILURE = "UPDATE_MANUFACTURER_FAILURE";

export const DELETE_MANUFACTURER_REQUEST = "DELETE_MANUFACTURER_REQUEST";
export const DELETE_MANUFACTURER_SUCCESS = "DELETE_MANUFACTURER_SUCCESS";
export const DELETE_MANUFACTURER_FAILURE = "DELETE_MANUFACTURER_FAILURE";

export const FETCH_MANUFACTURER_METADATA_REQUEST =
  "FETCH_MANUFACTURER_METADATA_REQUEST";
export const FETCH_MANUFACTURER_METADATA_SUCCESS =
  "FETCH_MANUFACTURER_METADATA_SUCCESS";
export const FETCH_MANUFACTURER_METADATA_FAILURE =
  "FETCH_MANUFACTURER_METADATA_FAILURE";

export const ADD_MANUFACTURER_METADATA_REQUEST =
  "ADD_MANUFACTURER_METADATA_REQUEST";
export const ADD_MANUFACTURER_METADATA_SUCCESS =
  "ADD_MANUFACTURER_METADATA_SUCCESS";
export const ADD_MANUFACTURER_METADATA_FAILURE =
  "ADD_MANUFACTURER_METADATA_FAILURE";
