// Dashboard Action Types
export const FETCH_DASHBOARD_STATISTICS_REQUEST = "FETCH_DASHBOARD_STATISTICS_REQUEST";
export const FETCH_DASHBOARD_STATISTICS_SUCCESS = "FETCH_DASHBOARD_STATISTICS_SUCCESS";
export const FETCH_DASHBOARD_STATISTICS_FAILURE = "FETCH_DASHBOARD_STATISTICS_FAILURE"; 