// Fetch Piece Images
export const FETCH_PIECE_IMAGES_REQUEST = 'FETCH_PIECE_IMAGES_REQUEST';
export const FETCH_PIECE_IMAGES_SUCCESS = 'FETCH_PIECE_IMAGES_SUCCESS';
export const FETCH_PIECE_IMAGES_FAILURE = 'FETCH_PIECE_IMAGES_FAILURE';

// Upload Piece Image
export const UPLOAD_PIECE_IMAGE_REQUEST = 'UPLOAD_PIECE_IMAGE_REQUEST';
export const UPLOAD_PIECE_IMAGE_SUCCESS = 'UPLOAD_PIECE_IMAGE_SUCCESS';
export const UPLOAD_PIECE_IMAGE_FAILURE = 'UPLOAD_PIECE_IMAGE_FAILURE';

// Update Piece Image
export const UPDATE_PIECE_IMAGE_REQUEST = 'UPDATE_PIECE_IMAGE_REQUEST';
export const UPDATE_PIECE_IMAGE_SUCCESS = 'UPDATE_PIECE_IMAGE_SUCCESS';
export const UPDATE_PIECE_IMAGE_FAILURE = 'UPDATE_PIECE_IMAGE_FAILURE';

// Delete Piece Image
export const DELETE_PIECE_IMAGE_REQUEST = 'DELETE_PIECE_IMAGE_REQUEST';
export const DELETE_PIECE_IMAGE_SUCCESS = 'DELETE_PIECE_IMAGE_SUCCESS';
export const DELETE_PIECE_IMAGE_FAILURE = 'DELETE_PIECE_IMAGE_FAILURE';

// Reorder Piece Images
export const REORDER_PIECE_IMAGES_REQUEST = 'REORDER_PIECE_IMAGES_REQUEST';
export const REORDER_PIECE_IMAGES_SUCCESS = 'REORDER_PIECE_IMAGES_SUCCESS';
export const REORDER_PIECE_IMAGES_FAILURE = 'REORDER_PIECE_IMAGES_FAILURE';

// Set Primary Piece Image
export const SET_PRIMARY_PIECE_IMAGE_REQUEST = 'SET_PRIMARY_PIECE_IMAGE_REQUEST';
export const SET_PRIMARY_PIECE_IMAGE_SUCCESS = 'SET_PRIMARY_PIECE_IMAGE_SUCCESS';
export const SET_PRIMARY_PIECE_IMAGE_FAILURE = 'SET_PRIMARY_PIECE_IMAGE_FAILURE'; 