export const FETCH_PERSONS_REQUEST = "FETCH_PERSONS_REQUEST";
export const FETCH_PERSONS_SUCCESS = "FETCH_PERSONS_SUCCESS";
export const FETCH_PERSONS_FAILURE = "FETCH_PERSONS_FAILURE";

export const FETCH_PERSON_BY_ID_REQUEST = "FETCH_PERSON_BY_ID_REQUEST";
export const FETCH_PERSON_BY_ID_SUCCESS = "FETCH_PERSON_BY_ID_SUCCESS";
export const FETCH_PERSON_BY_ID_FAILURE = "FETCH_PERSON_BY_ID_FAILURE";

export const CREATE_PERSON_REQUEST = "CREATE_PERSON_REQUEST";
export const CREATE_PERSON_SUCCESS = "CREATE_PERSON_SUCCESS";
export const CREATE_PERSON_FAILURE = "CREATE_PERSON_FAILURE";

export const UPDATE_PERSON_REQUEST = "UPDATE_PERSON_REQUEST";
export const UPDATE_PERSON_SUCCESS = "UPDATE_PERSON_SUCCESS";
export const UPDATE_PERSON_FAILURE = "UPDATE_PERSON_FAILURE";

export const DELETE_PERSON_REQUEST = "DELETE_PERSON_REQUEST";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";
export const DELETE_PERSON_FAILURE = "DELETE_PERSON_FAILURE";

export const FETCH_PERSON_TYPES_REQUEST = "FETCH_PERSON_TYPES_REQUEST";
export const FETCH_PERSON_TYPES_SUCCESS = "FETCH_PERSON_TYPES_SUCCESS";
export const FETCH_PERSON_TYPES_FAILURE = "FETCH_PERSON_TYPES_FAILURE";

export const FETCH_ADDRESS_TYPES_REQUEST = "FETCH_ADDRESS_TYPES_REQUEST";
export const FETCH_ADDRESS_TYPES_SUCCESS = "FETCH_ADDRESS_TYPES_SUCCESS";
export const FETCH_ADDRESS_TYPES_FAILURE = "FETCH_ADDRESS_TYPES_FAILURE";

export const CLEAR_CREATED_PERSON = "CLEAR_CREATED_PERSON";
