export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const RENEW_SESSION_REQUEST = "RENEW_SESSION_REQUEST";
export const RENEW_SESSION_SUCCESS = "RENEW_SESSION_SUCCESS";
export const RENEW_SESSION_FAILURE = "RENEW_SESSION_FAILURE";

export const UPDATE_TOKEN = "UPDATE_TOKEN";
