export const FETCH_PROPOSALS_REQUEST = "FETCH_PROPOSALS_REQUEST";
export const FETCH_PROPOSALS_SUCCESS = "FETCH_PROPOSALS_SUCCESS";
export const FETCH_PROPOSALS_FAILURE = "FETCH_PROPOSALS_FAILURE";

export const FETCH_PROPOSAL_BY_ID_REQUEST = "FETCH_PROPOSAL_BY_ID_REQUEST";
export const FETCH_PROPOSAL_BY_ID_SUCCESS = "FETCH_PROPOSAL_BY_ID_SUCCESS";
export const FETCH_PROPOSAL_BY_ID_FAILURE = "FETCH_PROPOSAL_BY_ID_FAILURE";

export const CREATE_PROPOSAL_REQUEST = "CREATE_PROPOSAL_REQUEST";
export const CREATE_PROPOSAL_SUCCESS = "CREATE_PROPOSAL_SUCCESS";
export const CREATE_PROPOSAL_FAILURE = "CREATE_PROPOSAL_FAILURE";

export const UPDATE_PROPOSAL_REQUEST = "UPDATE_PROPOSAL_REQUEST";
export const UPDATE_PROPOSAL_SUCCESS = "UPDATE_PROPOSAL_SUCCESS";
export const UPDATE_PROPOSAL_FAILURE = "UPDATE_PROPOSAL_FAILURE";

export const DELETE_PROPOSAL_REQUEST = "DELETE_PROPOSAL_REQUEST";
export const DELETE_PROPOSAL_SUCCESS = "DELETE_PROPOSAL_SUCCESS";
export const DELETE_PROPOSAL_FAILURE = "DELETE_PROPOSAL_FAILURE";

// PDF Generation
export const GENERATE_PROPOSAL_PDF_REQUEST = 'GENERATE_PROPOSAL_PDF_REQUEST';
export const GENERATE_PROPOSAL_PDF_SUCCESS = 'GENERATE_PROPOSAL_PDF_SUCCESS';
export const GENERATE_PROPOSAL_PDF_FAILURE = 'GENERATE_PROPOSAL_PDF_FAILURE';

// PDF Snapshots
export const FETCH_PDF_SNAPSHOTS_REQUEST = 'FETCH_PDF_SNAPSHOTS_REQUEST';
export const FETCH_PDF_SNAPSHOTS_SUCCESS = 'FETCH_PDF_SNAPSHOTS_SUCCESS';
export const FETCH_PDF_SNAPSHOTS_FAILURE = 'FETCH_PDF_SNAPSHOTS_FAILURE';

// Order Conversion
export const CONVERT_PROPOSAL_TO_ORDER_REQUEST = 'CONVERT_PROPOSAL_TO_ORDER_REQUEST';
export const CONVERT_PROPOSAL_TO_ORDER_SUCCESS = 'CONVERT_PROPOSAL_TO_ORDER_SUCCESS';
export const CONVERT_PROPOSAL_TO_ORDER_FAILURE = 'CONVERT_PROPOSAL_TO_ORDER_FAILURE';

export const UPLOAD_ITEM_IMAGE_REQUEST = "UPLOAD_ITEM_IMAGE_REQUEST";
export const UPLOAD_ITEM_IMAGE_SUCCESS = "UPLOAD_ITEM_IMAGE_SUCCESS";
export const UPLOAD_ITEM_IMAGE_FAILURE = "UPLOAD_ITEM_IMAGE_FAILURE";

export const UPLOAD_TEMP_IMAGE_REQUEST = "UPLOAD_TEMP_IMAGE_REQUEST";
export const UPLOAD_TEMP_IMAGE_SUCCESS = "UPLOAD_TEMP_IMAGE_SUCCESS";
export const UPLOAD_TEMP_IMAGE_FAILURE = "UPLOAD_TEMP_IMAGE_FAILURE";

export const CLEAR_PROPOSAL_PDF = "CLEAR_PROPOSAL_PDF";

// Image Management
export const UPDATE_ITEM_IMAGE_DESCRIPTION_REQUEST = 'UPDATE_ITEM_IMAGE_DESCRIPTION_REQUEST';
export const UPDATE_ITEM_IMAGE_DESCRIPTION_SUCCESS = 'UPDATE_ITEM_IMAGE_DESCRIPTION_SUCCESS';
export const UPDATE_ITEM_IMAGE_DESCRIPTION_FAILURE = 'UPDATE_ITEM_IMAGE_DESCRIPTION_FAILURE';

export const REORDER_ITEM_IMAGES_REQUEST = 'REORDER_ITEM_IMAGES_REQUEST';
export const REORDER_ITEM_IMAGES_SUCCESS = 'REORDER_ITEM_IMAGES_SUCCESS';
export const REORDER_ITEM_IMAGES_FAILURE = 'REORDER_ITEM_IMAGES_FAILURE';

export const DELETE_ITEM_IMAGE_REQUEST = 'DELETE_ITEM_IMAGE_REQUEST';
export const DELETE_ITEM_IMAGE_SUCCESS = 'DELETE_ITEM_IMAGE_SUCCESS';
export const DELETE_ITEM_IMAGE_FAILURE = 'DELETE_ITEM_IMAGE_FAILURE';

export const UPLOAD_ADDITIONAL_ITEM_IMAGE_REQUEST = 'UPLOAD_ADDITIONAL_ITEM_IMAGE_REQUEST';
export const UPLOAD_ADDITIONAL_ITEM_IMAGE_SUCCESS = 'UPLOAD_ADDITIONAL_ITEM_IMAGE_SUCCESS';
export const UPLOAD_ADDITIONAL_ITEM_IMAGE_FAILURE = 'UPLOAD_ADDITIONAL_ITEM_IMAGE_FAILURE';

export const UPDATE_PROPOSAL_OPTIMISTICALLY = 'UPDATE_PROPOSAL_OPTIMISTICALLY';

// Custom Section Image Upload
export const UPLOAD_CUSTOM_SECTION_IMAGE_REQUEST = 'UPLOAD_CUSTOM_SECTION_IMAGE_REQUEST';
export const UPLOAD_CUSTOM_SECTION_IMAGE_SUCCESS = 'UPLOAD_CUSTOM_SECTION_IMAGE_SUCCESS';
export const UPLOAD_CUSTOM_SECTION_IMAGE_FAILURE = 'UPLOAD_CUSTOM_SECTION_IMAGE_FAILURE';
